
name: Build-Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Checkout Apian dependencies (P2pNet)
      uses: actions/checkout@v2
      with:
        repository: Apian-Framework/Apian.Net
    - name: Checkout Apian dependencies (Apian)
      uses: actions/checkout@v2
      with:
        repository: Apian-Framework/Apian.Net
    - name: Checkout Apian dependencies (NotUnityEngine)
      uses: actions/checkout@v2
      with:
        repository: Apian-Framework/NotUnityEngine
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal